<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Laminas\Form\Form $form
 */
?>
<?php
    $translate = $this->plugin('translate');
    $this->headLink()->prependStylesheet($this->assetUrl('css/advanced-search.css', 'Omeka'));
    $this->headScript()->appendFile($this->assetUrl('js/advanced-search.js', 'Omeka'));

    $availableFields = $this->searchForm()->getAvailableSearchFields();
    $availableFieldsOptions = array_map(function ($field) {
        return [
            'value' => $field['name'],
            'label' => $field['label'],
            'attributes' => [
                'data-valid-operators' => implode(' ', $field['valid_operators'] ?? []),
            ],
        ];
    }, $availableFields);
    $availableOperators = $this->searchForm()->getAvailableOperators();
    $availableOperatorsOptions = array_map(function ($operator) {
        return [
            'value' => $operator['name'],
            'label' => $operator['display_name'],
            'attributes' => $operator['proximity_support'] ? ['data-proximity-support' => true] : [],
        ];
    }, $availableOperators);
    $searchPage = $form->getOption('search_page');
    $settings = $searchPage->settings();
    $proximitySetting = $settings['form']['proximity'] ?? false;

    $form->prepare();
    $form->setAttribute('id', 'search-form-standard');
?>
<?php echo $this->form()->openTag($form); ?>
<?php echo $this->formRow($form->get('q')); ?>

<?php $query = $this->params()->fromQuery(); ?>

<?php if (!empty($availableFieldsOptions)): ?>
    <div class="field">
        <div class="field-meta">
            <label><?php echo $translate('Filters'); ?></label>
        </div>
        <div class="inputs">
            <?php echo $this->partial('search/form/standard-match-group', [
                'availableFieldsOptions' => $availableFieldsOptions,
                'availableOperatorsOptions' => $availableOperatorsOptions,
                'data' => $query['filters'] ?? [],
                'namePrefix' => 'filters',
                'mainGroup' => true,
                'proximitySetting' => $proximitySetting,
            ]); ?>
        </div>
    </div>

    <template id="template-search-filter">
        <div class="search-form-standard-match-group-item">
            <?php echo $this->partial('search/form/standard-match-group-filter', [
                'availableFieldsOptions' => $availableFieldsOptions,
                'availableOperatorsOptions' => $availableOperatorsOptions,
                'query' => [],
                'namePrefix' => '__placeholder__',
                'proximitySetting' => $proximitySetting,
            ]); ?>
        </div>
    </template>

    <template id="template-search-group">
        <div class="search-form-standard-match-group-item">
            <?php echo $this->partial('search/form/standard-match-group', [
                'availableFieldsOptions' => $availableFieldsOptions,
                'availableOperatorsOptions' => $availableOperatorsOptions,
                'data' => [],
                'namePrefix' => '__placeholder__',
                'mainGroup' => false,
                'proximitySetting' => $proximitySetting,
            ]); ?>
        </div>
    </template>

    <script>
        $(document).ready(function () {
            Omeka.prepareSearchForm($('#search-form-standard'));
            initProximityVisibility();
            $('#search-form-standard').on('change', '.search-form-standard-filter-operator', function () {
                toggleProximityVisibility($(this));
            });

            $('#search-form-standard').on('click', '.search-add-filter', function (ev) {
                ev.preventDefault();
                insertFilterBefore(this.closest('.search-form-standard-match-group-item'));
                renameAllFormControls();
                initProximityVisibility();
            });

            $('#search-form-standard').on('click', '.search-add-group', function (ev) {
                ev.preventDefault();
                const template = document.getElementById('template-search-group');
                const group = template.content.cloneNode(true).firstElementChild;
                this.closest('.search-form-standard-match-group-item').insertAdjacentElement('beforebegin', group);

                renameAllFormControls();
                initProximityVisibility();
            });

            $('#search-form-standard').on('click', '.search-delete-filter', function (ev) {
                ev.preventDefault();
                $(this).closest('.search-form-standard-match-group-item').remove();
                renameAllFormControls();
            });

            // Disable operators that are not valid to use with the selected field
            $('#search-form-standard').on('change', '.search-form-standard-filter-field', function () {
                const validOperators = $(this).find('option:selected').attr('data-valid-operators').split(' ');
                const options = $(this).closest('.search-form-standard-match-group-item').find('.search-form-standard-filter-operator').find('option');
                options.attr('disabled', false);
                options.each(function () {
                    const option = $(this);
                    if (!validOperators.includes(option.val())) {
                        option.attr('disabled', true);
                        option.prop('selected', false);
                    }
                })
            });
            $('#search-form-standard .search-form-standard-filter-field').trigger('change');

            function insertFilterBefore(element) {
                const template = document.getElementById('template-search-filter');
                const filter = template.content.cloneNode(true).firstElementChild;
                element.insertAdjacentElement('beforebegin', filter);
            }

            function renameFormControls (element, namePrefix) {
                $(element).children('select').attr('name', namePrefix + '[match]');

                const items = $(element)
                    .children('.search-form-standard-match-group-items')
                    .children('.search-form-standard-match-group-item');

                for (let i = 0; i < items.length; i++) {
                    const item = items.get(i);
                    $(item).children('input,select').each(function () {
                        const match = $(this).attr('name').match(/\[([^[]+)\]$/);
                        if (match) {
                            $(this).attr('name', namePrefix + '[queries][' + i + '][' + match[1] + ']');
                        }
                    });
                    $(item).children('.search-form-standard-match-group').each(function () {
                        renameFormControls(this, namePrefix + '[queries][' + i + ']');
                    });
                }
            }

            function renameAllFormControls () {
                const mainGroup = document.querySelector('#search-form-standard > .field > .inputs > .search-form-standard-match-group');
                renameFormControls(mainGroup, 'filters');
            }

            // Hide proximity input if "Contains all words" operator is not selected
            function initProximityVisibility() {
                const operatorInputs = $('#search-form-standard').find('.search-form-standard-filter-operator');
                $(operatorInputs).each(function () {
                    toggleProximityVisibility($(this));
               });
            }
           
            function toggleProximityVisibility(element) {
                const operatorSupportProx = $(element).find('option:selected').attr('data-proximity-support');
                const proxElement = $(element).siblings('.search-form-standard-filter-proximity');
                if (operatorSupportProx) {
                    proxElement.show();
                } else {
                    proxElement.hide();
                }
            };
        });
    </script>
<?php endif; ?>

<?php foreach ($settings['form']['elements'] ?? [] as $formElementData): ?>
    <?= $this->searchFormElement()->form($searchPage, $query, $formElementData) ?>
<?php endforeach; ?>

<?php echo $this->formRow($form->get('has_media')); ?>

<button type="submit"><?php echo $translate('Search'); ?></button>

<?php echo $this->form()->closeTag(); ?>
