<?php
/*
 * Copyright BibLibre, 2016
 *
 * This software is governed by the CeCILL license under French law and abiding
 * by the rules of distribution of free software.  You can use, modify and/ or
 * redistribute the software under the terms of the CeCILL license as circulated
 * by CEA, CNRS and INRIA at the following URL "http://www.cecill.info".
 *
 * As a counterpart to the access to the source code and rights to copy, modify
 * and redistribute granted by the license, users are provided only with a
 * limited warranty and the software's author, the holder of the economic
 * rights, and the successive licensors have only limited liability.
 *
 * In this respect, the user's attention is drawn to the risks associated with
 * loading, using, modifying and/or developing or reproducing the software by
 * the user in light of its specific status of free software, that may mean that
 * it is complicated to manipulate, and that also therefore means that it is
 * reserved for developers and experienced professionals having in-depth
 * computer knowledge. Users are therefore encouraged to load and test the
 * software's suitability as regards their requirements in conditions enabling
 * the security of their systems and/or data to be ensured and, more generally,
 * to use and operate it in the same conditions as regards security.
 *
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL license and that you accept its terms.
 */
?>

<?php $escape = $this->plugin('escapeHtml'); ?>

<?php echo $this->pageTitle($this->translate('Search configuration')); ?>

<div id="page-actions">
    <a class="button" href="<?php echo $this->url('admin/search/index', ['action' => 'add']); ?>">Add new index</a>
    <?php if (!empty($search_indexes)): ?>
        <a class="button" href="<?php echo $this->url('admin/search/page', ['action' => 'add']); ?>">Add new page</a>
    <?php endif; ?>
</div>

<h2>Indexes</h2>
<?php if (count($search_indexes) > 0): ?>
    <table class="tablesaw">
        <thead>
            <tr>
                <th>Name</th>
                <th>Adapter</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($search_indexes as $search_index): ?>
                <tr>
                    <td>
                        <ul class="actions">
                            <?php if ($search_index->adapter()): ?>
                                <li>
                                    <?php
                                        echo $search_index->link('', 'configure', [
                                            'class' => 'o-icon-configure',
                                            'title' => $this->translate('Configure'),
                                        ]);
                                    ?>
                                </li>
                                <li>
                                    <?php
                                        echo $search_index->link('', 'index', [
                                            'class' => 'o-icon- fa fa-refresh',
                                            'title' => $this->translate('Reindex all'),
                                        ]);
                                    ?>
                                </li>
                            <?php endif; ?>
                            <li>
                                <a href="#"
                                data-sidebar-content-url="<?php echo $escape($search_index->url('delete-confirm')); ?>"
                                class="o-icon-delete sidebar-content"
                                aria-label="<?php echo $escape($this->translate('Delete')); ?>"
                                title="<?php echo $escape($this->translate('Delete')); ?>"></a>
                            </li>
                        </ul>
                        <?php echo $search_index->name(); ?>
                    </td>
                    <td><?php echo $search_index->adapterLabel(); ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php else: ?>
    <p><?php echo $this->translate('No search indexes created yet.'); ?></p>
<?php endif; ?>

<h2>Pages</h2>
<?php if (count($search_pages) > 0): ?>
    <table class="tablesaw">
        <thead>
            <tr>
                <th>Name</th>
                <th>Path</th>
                <th>Index</th>
                <th>Form</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($search_pages as $search_page): ?>
                <tr>
                    <td>
                        <ul class="actions">
                            <li>
                                <?php
                                    echo $search_page->link('', 'edit', [
                                        'class' => 'o-icon-edit',
                                        'title' => $this->translate('Edit'),
                                    ]);
                                ?>
                            </li>
                            <li>
                                <?php
                                    echo $search_page->link('', 'configure', [
                                        'class' => 'o-icon-configure',
                                        'title' => $this->translate('Configure'),
                                    ]);
                                ?>
                            </li>
                            <li>
                                <a href="#"
                                data-sidebar-content-url="<?php echo $escape($search_page->url('delete-confirm')); ?>"
                                class="o-icon-delete sidebar-content"
                                aria-label="<?php echo $escape($this->translate('Delete')); ?>"
                                title="<?php echo $escape($this->translate('Delete')); ?>"></a>
                            </li>
                        </ul>
                        <?php echo $search_page->name(); ?>
                    </td>
                    <td><?php echo $search_page->path(); ?></td>
                    <td><?php echo $search_page->index()->name(); ?></td>
                    <td>
                        <?php
                            $formAdapter = $search_page->formAdapter();
                            if ($formAdapter) {
                                echo $formAdapter->getLabel();
                            } else {
                                echo $search_page->formAdapterName();
                            }
                        ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php else: ?>
    <p><?php echo $this->translate('No search pages created yet.'); ?></p>
<?php endif; ?>

<div class="sidebar">
    <a href="#"
        class="sidebar-close o-icon-close"
        aria-label="<?php echo $escape($this->translate('Close')); ?>"
        title="<?php echo $escape($this->translate('Close')); ?>"></a>
    <div class="sidebar-content"></div>
</div>
