<?php
/*
 * Copyright BibLibre, 2016-2017
 * Copyright Daniel Berthereau, 2017-2019
 *
 * This software is governed by the CeCILL license under French law and abiding
 * by the rules of distribution of free software.  You can use, modify and/ or
 * redistribute the software under the terms of the CeCILL license as circulated
 * by CEA, CNRS and INRIA at the following URL "http://www.cecill.info".
 *
 * As a counterpart to the access to the source code and rights to copy, modify
 * and redistribute granted by the license, users are provided only with a
 * limited warranty and the software's author, the holder of the economic
 * rights, and the successive licensors have only limited liability.
 *
 * In this respect, the user's attention is drawn to the risks associated with
 * loading, using, modifying and/or developing or reproducing the software by
 * the user in light of its specific status of free software, that may mean that
 * it is complicated to manipulate, and that also therefore means that it is
 * reserved for developers and experienced professionals having in-depth
 * computer knowledge. Users are therefore encouraged to load and test the
 * software's suitability as regards their requirements in conditions enabling
 * the security of their systems and/or data to be ensured and, more generally,
 * to use and operate it in the same conditions as regards security.
 *
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL license and that you accept its terms.
 */

/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Search\Api\Representation\SearchPageRepresentation $searchPage
 * @var \Search\Form\Admin\SearchPageConfigureForm|\Search\Form\Admin\SearchPageConfigureSimpleForm $form
 */

$translate = $this->plugin('translate');
$formCollection = $this->plugin('formCollection');
$formRow = $this->plugin('formRow');

$isSimple = $form instanceof \Search\Form\Admin\SearchPageConfigureSimpleForm;

$assetUrl = $this->plugin('assetUrl');
$this->headLink()
    ->appendStylesheet($assetUrl('jquery-ui.min.css', 'jQueryUI'))
    ->appendStylesheet($assetUrl('css/search-page-configure.css', 'Search'));
$this->headScript()
    ->appendFile($assetUrl('jquery-ui.min.js', 'jQueryUI'))
    ->appendFile($assetUrl('js/search-admin.js', 'Search'));

$index = $searchPage->index();
$adapter = $index ? $index->adapter() : null;
if (empty($adapter)) {
    return;
}

$availableFields = $adapter->getAvailableFields($index);

$form->prepare();
?>

<?= $this->pageTitle(sprintf($translate('Configure search page "%s"'), $searchPage->name())) ?>

<?= $this->form()->openTag($form) ?>
<div id="page-actions">
    <button><?= $translate('Save configuration') ?></button>
</div>

<p>
<?php if ($isSimple): ?>
    <?= $this->hyperlink($translate('Use visual form.'), $this->url('admin/search/page-id', [], ['query' => ['form' => 'visual']], true)) ?>
    <?php if (count($availableFields) > 200): ?>
    <?= $translate('Warning: you have more than 200 properties, the form will be slow to load.') ?>
    <?php endif; ?>
<?php else: ?>
    <?= $this->hyperlink($translate('Use simple form.'), $this->url('admin/search/page-id', [], ['query' => ['form' => 'simple']], true)) ?>
<?php endif; ?>
</p>

<?php foreach ($form->getElements() as $element): ?>
    <?= $formRow($element); ?>
<?php endforeach; ?>

<?php foreach ($form->getFieldsets() as $fieldset): ?>
    <div data-sortable="<?= $fieldset->getAttribute('data-sortable') ?>">
        <h2><?= $fieldset->getLabel() ?></h2>
        <?php foreach ($fieldset->getFieldsets() as $subfieldset): ?>
            <?= $formCollection($subfieldset) ?>
        <?php endforeach; ?>

        <?php foreach ($fieldset->getElements() as $element): ?>
            <?= $formRow($element) ?>
        <?php endforeach; ?>
    </div>
<?php endforeach; ?>

<?= $this->form()->closeTag() ?>
