<?php
/*
 * Copyright BibLibre, 2016-2017
 * Copyright Daniel Berthereau, 2017-2018
 *
 * This software is governed by the CeCILL license under French law and abiding
 * by the rules of distribution of free software.  You can use, modify and/ or
 * redistribute the software under the terms of the CeCILL license as circulated
 * by CEA, CNRS and INRIA at the following URL "http://www.cecill.info".
 *
 * As a counterpart to the access to the source code and rights to copy, modify
 * and redistribute granted by the license, users are provided only with a
 * limited warranty and the software's author, the holder of the economic
 * rights, and the successive licensors have only limited liability.
 *
 * In this respect, the user's attention is drawn to the risks associated with
 * loading, using, modifying and/or developing or reproducing the software by
 * the user in light of its specific status of free software, that may mean that
 * it is complicated to manipulate, and that also therefore means that it is
 * reserved for developers and experienced professionals having in-depth
 * computer knowledge. Users are therefore encouraged to load and test the
 * software's suitability as regards their requirements in conditions enabling
 * the security of their systems and/or data to be ensured and, more generally,
 * to use and operate it in the same conditions as regards security.
 *
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL license and that you accept its terms.
 */

/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Search\Form\Admin\SearchPageForm $form
 */

$translate = $this->plugin('translate');
$this->headLink()->appendStylesheet($this->assetUrl('jquery-ui.min.css', 'jQueryUI'));
$this->headScript()->appendFile($this->assetUrl('jquery-ui.min.js', 'jQueryUI'));
$this->headLink()->appendStylesheet($this->assetUrl('css/search-page-configure.css', 'Search'));
$this->headScript()->appendFile($this->assetUrl('js/search-admin.js', 'Search'));
?>

<?php $form->prepare(); ?>
<?php $searchPage = $form->getOption('search_page'); ?>

<?php echo $this->pageTitle(sprintf($translate('Configure search page "%s"'), $searchPage->name())); ?>

<?php echo $this->form()->openTag($form); ?>
<div id="page-actions">
    <button><?php echo $translate('Save configuration'); ?></button>
</div>

<?php foreach ($form->getElements() as $element): ?>
    <?php echo $this->formRow($element); ?>
<?php endforeach; ?>

<?php foreach ($form->getFieldsets() as $fieldset): ?>
    <div data-sortable="<?php echo $fieldset->getAttribute('data-sortable'); ?>">
        <h2><?php echo $fieldset->getLabel() ?></h2>
        <?php foreach ($fieldset->getFieldsets() as $subfieldset): ?>
            <?php echo $this->formCollection($subfieldset); ?>
        <?php endforeach; ?>

        <?php foreach ($fieldset->getElements() as $element): ?>
            <?php echo $this->formRow($element); ?>
        <?php endforeach; ?>
    </div>
<?php endforeach; ?>

<?php echo $this->form()->closeTag(); ?>
