language: php

os: linux
dist: bionic

services:
  - mysql

php:
  - 7.2
  - 7.3
  - 7.4

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - nvm install 12
  - nvm use 12

install:
  - cd ../..
  - git clone --depth 1 https://github.com/omeka/omeka-s.git
  - cp -a $(readlink -e $(cd -)) omeka-s/modules/Search
  - cd omeka-s
  - npm install
  - ./node_modules/gulp/bin/gulp.js init

before_script:
  - mysql -e "create database IF NOT EXISTS omeka_test;" -uroot
  - sed -i 's/^host.*/host = "localhost"/' application/test/config/database.ini
  - sed -i 's/^user.*/user = "root"/' application/test/config/database.ini
  - sed -i 's/^dbname.*/dbname = "omeka_test"/' application/test/config/database.ini
  - cd modules/Search
  - composer install
  - cd test

script: ../../../vendor/bin/phpunit
