<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var array $fieldData
 */
?>
<li class="fields-field row"
    data-field-name="<?php echo $this->escapeHtml($fieldData['name']); ?>"
    data-field-data="<?php echo $this->escapeHtml(json_encode($fieldData)); ?>">
    <span class="sortable-handle"></span>
    <span class="fields-field-restore" style="display: none;"><?php echo $this->translate('Form element to be removed'); ?></span>
    <?php $label = $this->searchFormElement()->label($fieldData); ?>
    <span class="fields-field-label"><?php echo $this->escapeHtml($label); ?></span>
    <ul class="actions">
        <li><?php echo $this->hyperlink('', [], [
            'class' => 'o-icon-edit fields-field-edit-button',
            'title' => $this->translate('Edit form element'),
        ]); ?></li>
        <li><?php echo $this->hyperlink('', [], [
            'class' => 'o-icon-delete fields-field-remove-button',
            'title' => $this->translate('Remove form element'),
        ]); ?></li>
        <li><?php echo $this->hyperlink('', [], [
            'class' => 'o-icon-undo fields-field-restore-button',
            'title' => $this->translate('Restore form element'),
            'style' => 'display: none;',
        ]); ?></li>
    </ul>
</li>
