<a href="#" class="sidebar-close o-icon-close"><span class="screen-reader-text"><?php echo $this->translate('Close'); ?></span></a>
<div class="sidebar-content">
    <div class="confirm-main">
        <div id="fields-field-form">
            <h3><?php echo $this->translate('Edit form element'); ?></h3>
            <?php
            $nameInput = new \Laminas\Form\Element\Text('name');
            $nameInput->setLabel($this->translate('Name'));
            $nameInput->setValue($this->searchFormElement()->label($fieldData));
            $nameInput->setAttribute('disabled', true);
            echo $this->formRow($nameInput);
            ?>

            <?= $this->searchFormElement()->configForm($searchPage, $fieldData); ?>
        </div>
    </div>
    <div class="confirm-panel">
        <button type="button" id="fields-field-set-button"><?php echo $this->translate('Set form element'); ?></button>
    </div>
</div>
