<?php
/*
 * Copyright BibLibre, 2016
 * Copyright Daniel Berthereau, 2017-2018
 *
 * This software is governed by the CeCILL license under French law and abiding
 * by the rules of distribution of free software.  You can use, modify and/ or
 * redistribute the software under the terms of the CeCILL license as circulated
 * by CEA, CNRS and INRIA at the following URL "http://www.cecill.info".
 *
 * As a counterpart to the access to the source code and rights to copy, modify
 * and redistribute granted by the license, users are provided only with a
 * limited warranty and the software's author, the holder of the economic
 * rights, and the successive licensors have only limited liability.
 *
 * In this respect, the user's attention is drawn to the risks associated with
 * loading, using, modifying and/or developing or reproducing the software by
 * the user in light of its specific status of free software, that may mean that
 * it is complicated to manipulate, and that also therefore means that it is
 * reserved for developers and experienced professionals having in-depth
 * computer knowledge. Users are therefore encouraged to load and test the
 * software's suitability as regards their requirements in conditions enabling
 * the security of their systems and/or data to be ensured and, more generally,
 * to use and operate it in the same conditions as regards security.
 *
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL license and that you accept its terms.
 */
?>


<?php
    $escape = $this->plugin('escapeHtml');
    $this->headLink()->appendStylesheet($this->assetUrl('css/search.css', 'Search'));
    $this->headScript()->appendFile($this->assetUrl('js/search.js', 'Search'));
    $user = $this->identity();
?>

<?php echo $this->pageTitle($this->translate('Search'), 2); ?> 

<?php echo $this->messages(); ?>

<div id="search-form-wrapper">
    <?php echo $this->searchForm(); ?>
</div>
        
    <?php if (isset($response) && !empty($response->getSuggestTerms()) && $spellchecking) : ?> 
            <div class="suggestTerms"><?php echo $this->translate('Did you mean : ');
            foreach ($response->getSuggestTerms() as $suggestTerms) { ?>
            <?php
            $query->setQuery($suggestTerms['word']);
            $newQuery = $_GET;
            $newQuery['q'] = $query->getQuery();
            $newQuerySearch = $this->url(null, [], ['query' => $newQuery], true);
            ?>
                <button>
                    <a href = '<?php echo $newQuerySearch; ?>'>
                        <?php echo $suggestTerms['word']; ?>
                    </a>
                </button>
                <?php } ?>
            </div>
            <?php endif; ?>
    
<a href="#" id="search-form-show-link" style="display: none"><?php echo $this->translate('Edit search'); ?></a>

<?php if (isset($response)): ?>
    <div class="search-results-wrapper">
        <div class="search-results">
        
            <?php if ($response->getTotalResults() > 0): ?>
                <?php
                    echo $this->partial('search/results-header', [
                        'query' => $query,
                        'response' => $response,
                        'sortOptions' => $sortOptions,
                    ]);
                ?>

                <?php $itemSetsCount = $response->getResourceTotalResults('item_sets'); ?>
                <?php echo $this->partial('search/resource-list', [
                    'title' => sprintf($this->translatePlural('%s item set', '%s item sets', $itemSetsCount), $itemSetsCount),
                    'response' => $response,
                    'resourceName' => 'item_sets',
                    'site' => $site,
                ]);
                ?>

                <?php $itemsCount = $response->getResourceTotalResults('items'); ?>
                <?php echo $this->partial('search/resource-list', [
                    'title' => sprintf($this->translatePlural('%s item', '%s items', $itemsCount), $itemsCount),
                    'response' => $response,
                    'resourceName' => 'items',
                    'site' => $site
                ]); ?>

                <?php
                    echo $this->partial('search/results-footer', [
                        'query' => $query,
                        'response' => $response,
                        'sortOptions' => $sortOptions,
                    ]);
                ?>
            <?php else: ?>
                <div class="noresults"><?php echo $this->translate('Your query returned no results'); ?></div>
               
            <?php endif; ?>
            <?php if(isset($user) && $saveQueryParam) : ?>
            <form method="post" action="<?php echo $this->url('site/save-query', [], true)  ?>">
                <input id="save_site_id" type="hidden" name="site_id" value="<?php echo $site->id() ?>">
                <input id="save_search_page_id" type="hidden" name="search_page_id" value="<?php echo $searchPageId ?>">
                <input id="save_newquerystring" type="hidden" name="query_string" value='<?php echo $queryParams ?>'>
                <div>
                    <input id="save_newquerytitle" type="text" name="query_title" size="20" title="New query title" placeholder="<?php echo $this->translate('Title')?>" value="">
                </div>
                <div>
                    <textarea id="save_newquerydescription" type="text" rows="5" cols="30" name="query_description" title="New query description" placeholder="<?php echo $this->translate('Description')?>" value=""></textarea>
                </div>
                <div>
                    <input id="saveSearch" type="submit" value="<?php echo $this->translate('Save this query') ?>">
                </div>
            </form>
        </div>
<?php endif; ?>

        <?php echo $this->partial('search/facets', ['facets' => $facets]); ?>
    </div>
<?php endif; ?>

<script>
    $(document).ready(function() {
        $('#search-form-show-link').on('click', function (ev) {
            ev.preventDefault();
            $('#search-form-wrapper').show();
            $('#search-form-show-link').hide();
        });
        if (document.querySelector('.search-results')) {
            $('#search-form-wrapper').hide();
            $('#search-form-show-link').show();
        }

        $('.search-results-sort select').on('change', function() {
            Search.sortBy($(this).val());
        });

        $('.search-view-type-list').on('click', function(e) {
            e.preventDefault();
            Search.setViewType('list');
            $('.search-view-type').removeClass('active');
            $(this).addClass('active');
        });
        $('.search-view-type-grid').on('click', function(e) {
            e.preventDefault();
            Search.setViewType('grid');
            $('.search-view-type').removeClass('active');
            $(this).addClass('active');
        });

        var view_type = localStorage.getItem('search_view_type');
        if (!view_type) {
            view_type = 'list';
        }
        $('.search-view-type-' + view_type).click();
    });
</script>
