<?php
$this->headScript()->appendFile($this->assetUrl("js/facets.js", "Search"));
$settings = $this->searchCurrentPage()->settings();
$facetedFiltering =
    isset($settings["faceted_filtering"]) &&
    $settings["faceted_filtering"] === "1";
?>


<?php if (!empty($facets)): ?>
    <aside class="search-facets">
        <h2>
            <?php echo $this->translate("Facets"); ?>
            <?php if ($facetedFiltering): ?>
            <div class="actions">
                <button id="submit-facets"><?php echo $this->translate('Apply') ?></button>
                <button id="reset-facets"><?php echo $this->translate('Clear') ?></button>
            </div>
            <?php endif; ?>
        </h2>
        <?= $this->partial('search/active-facets') ?>
        <ul>
            <?php foreach ($settings['facets'] as $facetSettings): ?>
                <?php $name = $facetSettings['name']; ?>
                <?php $facet_display_limit = $facetSettings['facet_display_limit'] ?? 10; ?>
                <?php $facet_values = $facets[$name] ?? []; ?>
                <?php $operator = isset($facetSettings['operator']) ? $facetSettings['operator'] : 'AND'; ?>
                <?php if ($facet_values): ?>
                    <?php $visible_facets = array_slice($facet_values, 0, $facet_display_limit); ?>
                    <?php $hidden_facets = array_slice($facet_values, $facet_display_limit); ?>
                    <li class="search-facet" data-facet-name="<?= $this->escapeHtml($name) ?>">
                        <h3><?php echo $this->facetLabel($name); ?></h3>
                        <span class="search-facet-operator"><?= $this->escapeHtml($operator) ?></span>
                        <div>
                            <ul class="search-facet-items">
                                <?php foreach ($visible_facets as $facetValue): ?>
                                    <li class="search-facet-item">
                                        <?php echo $this->facetLink($name, $facetValue, $facetedFiltering); ?>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                        <?php if (!empty($hidden_facets)): ?>
                            <div class="hidden-facets">
                                <ul class="search-facet-items">
                                    <?php foreach ($hidden_facets as $hiddenValue): ?>
                                        <li class="search-facet-item">
                                            <?php echo $this->facetLink($name, $hiddenValue, $facetedFiltering); ?>
                                        </li>
                                    <?php endforeach; ?>
                                </ul>
                            </div>
                            <button class="search-facet-expand-button search-facet-toggle-btn">
                                <i class="fas fa-chevron-down"></i>
                                <?php echo $this->escapeHtml($settings["facet_limit_expand_label"]); ?>
                            </button>
                            <button class="search-facet-collapse-button search-facet-toggle-btn">
                                <i class="fas fa-chevron-up"></i>
                                <?php echo $this->escapeHtml($settings["facet_limit_collapse_label"]); ?>
                            </button>
                        <?php endif; ?>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </aside>
<?php endif; ?>
