<?php

/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var bool $active
 * @var string $name
 * @var mixed $value
 * @var string $url
 * @var int $count
 */
$this->headScript()->appendFile($this->assetUrl('js/facets.js', 'Search'));
?>
<div>
    <span class="<?php echo $active ? 'active' : 'inactive'; ?>">
        <?php if($facetedFiltering) : ?>
            <input type="checkbox"
                id="checkbox_<?php echo $id; ?>"
                name="selectedFacets[<?php echo $this->escapeHtml($name); ?>][]"
                value="<?php echo $this->escapeHtml($name); ?>"
                data-facet-name="<?php echo $this->escapeHtml($name); ?>"
                data-facet-value="<?php echo $this->escapeHtml($value); ?>"
               <?php echo $active ? 'checked' : ''; ?>
            />
            <label for="checkbox_<?php echo $id; ?>">
                <a href="<?php echo $this->escapeHtml($url); ?>"><?= $this->searchFacetValue($name, (string) $value) ?></a>
                (<?php echo $count; ?>)
            </label>
        <?php else : ?>
            <a href="<?php echo $this->escapeHtml($url); ?>"><?= $this->searchFacetValue($name, (string) $value) ?></a>
            (<?php echo $count; ?>)
        <?php endif ; ?>
    </span>
</div>