<?php 
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->headLink()->appendStylesheet($this->assetUrl('css/search.css', 'Search'));
?>

<?php if (!empty($term)) : ?>
    <span class="search-summary-details__filter-field">
        <?php echo $translate($field); ?>
    </span>
    <span class="search-summary-details__filter-operator">
        <i><?php echo $translate($operator); ?></i>
    </span>
    <span class="search-summary-details__filter-term">
        <?php echo '"' . $term . '"'; ?>
    </span>
<?php endif; ?>
           
