<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Search\Api\Representation\SearchIndexRepresentation $resource
 * @var string $resourceLabel
 * @var int $totalJobs
 * @var string $partialPath
 */

?>

<?= $this->searchIndexConfirm($this->resource, $this->resourceLabel, false, $totalJobs) ?>
<?php if (isset($this->partialPath)): ?>
    <?= $this->partial($this->partialPath) ?>
<?php endif; ?>
