<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Search\Api\Representation\SearchIndexRepresentation $resource
 * @var \Omeka\Form\ConfirmForm $form
 * @var string $wrapSidebar
 * @var string $resourceLabel
 * @var int $totalJobs
 */

$translate = $this->plugin('translate');

$this->form->setAttribute('action', $resource->url('index'));
$this->form->setButtonLabel($translate('Confirm reindex'));
?>

<?php if ($this->wrapSidebar): ?>
<div id="index" class="sidebar">
    <?= $this->hyperlink('', '#', ['class' => 'sidebar-close o-icon-close', 'title' => $translate('Close')]) ?>
<?php endif; ?>
    <div id="sidebar-confirm">
        <h3><?= sprintf($translate('Reindex "%s"'), $resource->name()) ?></h3>
        <p><?= $translate('Are you sure you would like to reindex this index?') ?></p>
        <p>
        <?= $translate('All the indexes will be cleared first, so the search will be unavailable for a while.') ?>
        <?= $translate('You may redirect the users on a clone of the current index temporary.') ?>
        </p>
        <p>
        <?= $translate('You may prefer to keep existing indexes and to start the indexing at the following resource id.') ?>
        <?= $translate('Set "1" to reindex all resources without clearing the current index.') ?>
        <input name="start_resource_id" placeholder="0" value="" type="number" form="confirmform" />
        </p>
        <p>
        <?= $translate('You may want to limit the reindexing to a resource type.') ?>
        <?php foreach ($resource->settings()['resources'] as $resourceName): ?>
        <input name="resource_names[]" value="<?= $resourceName ?>" type="checkbox" checked="checked" form="confirmform" /><?= $resourceName ?>
        <?php endforeach; ?>
        </p>
        <p>
        <?php if ($totalJobs): ?>
        <?= sprintf($translate('%d running indexings.'), $totalJobs) ?><br />
         <input name="force" type="checkbox" /><?= $translate('Force indexing') ?><br />
        <?php else: ?>
        <?= $translate('No running indexing: process can be launched.') ?>
        <?php endif; ?>
        </p>
        <?= $this->form($this->form) ?>
    </div>
<?php if ($this->wrapSidebar): ?>
</div>
<?php endif; ?>
